const data={
    products:[
        {
            _id:'1',
            name:'Nike Slim Shrit',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:450,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Adidas Fit Shrit',
            category:'Shirts',
            image:'/images/p2.jpeg',
            price:550,
            brand:'Adidas',
            rating:4.0,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Lacoste Free Shrit',
            category:'Shirts',
            image:'/images/p3.jpeg',
            price:450,
            brand:'Lacoste',
            rating:4.8,
            numReviews:17,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Nike Slim Pant',
            category:'Pants',
            image:'/images/p4.jpeg',
            price:350,
            brand:'Pants',
            rating:4.5,
            numReviews:14,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Puma Slim Pant',
            category:'Pants',
            image:'/images/p5.jpeg',
            price:650,
            brand:'Puma',
            rating:4.5,
            numReviews:1,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'Adidas Fit Pant',
            category:'Shirt Pant',
            image:'/images/p6.jpeg',
            price:750,
            brand:'Adidas',
            rating:4.9,
            numReviews:15,
            description:'high quality product',
        },

    ],
};


export default data ;